version: '3'
services:
  mongodb:
    image: 'mongo:4.2.1'
    container_name: 'my_mongo_container'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'recomendy_db'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - 27017:27017
